### ISSUE TITLE
Change abandoned guzzle dependency

### ISSUE THREAD

**Issue by SteenSchutt** [Penneo/sdk-php#22]
The guzzle package has been moved from guzzle/guzzle to guzzlehttp/guzzle. The dependency should be updated according to this change.

**Comment by kasperhartwich** [comment]
@janflora @ahmadnazir Can this be prioritized? The version 3.x you are using is 4-5 yers old and EOL.
We are now on version 6!
https://github.com/guzzle/guzzle#version-guidance

**Comment by ilmarspenneo** [comment]
Closing this as the current latest version of the SDK uses a supported version of guzzle.
