### ISSUE TITLE
readObject method in ApiConnector

### ISSUE THREAD

**Issue by Malek-Mohamed** [Penneo/sdk-php#62]
Hey, i noticed that there is a bug in the `readObject` method in the ApiConnector.php

`$response = self::callServer($object->getRelativeUrl() . '/' . $object->getId());`
   `if ($response === false) {`
            `return false;`
        `}`
The `callServer` method return 2 types either GuzzleHttp\Psr7\Response or NULL, so the `if ($response === false)` should be 
`if (!$response)` because it will never returns false.

This is may cause a possible bug if the $response is null and we try to getBody from it.

**Comment by clund-np** [comment]
Should be an easy fix, will there be a new release this month?

**Comment by Malek-Mohamed** [comment]
> Should be an easy fix, will there be a new release this month?

no idea when they gonna release it but they should do it soon.

**Comment by HeadCookie** [comment]
This was solved in #63 - thank you @Malek-Mohamed!
